describe('Weeks', function() {
  return it('fetches tasks', function() {
    fixture.preload("fixtures.json");
    return describe("Using fixtures", function() {
      beforeEach(module("todoListsApp"));
      beforeEach(inject(function($injector, $controller, $rootScope) {
        var $http, fixtures, scope;
        fixtures = fixture.load("fixtures.json");
        $http = $injector.get("$httpBackend");
        $http.expectGET("/documents").respond(200, fixtures[0]);
        scope = $rootScope.$new();
        $controller("WeeksController", {
          $scope: scope
        });
        $http.flush();
      }));
      return it("must fetch documents", function() {
        return expect(scope.tasks.length).toEqual(fixtures[0].length);
      });
    });
  });
});

// ---
// generated by coffee-script 1.9.2