describe("Task", function() {
  var $httpBackend, Task, newTask, testTasks;
  Task = void 0;
  $httpBackend = void 0;
  testTasks = [
    {
      done: false,
      id: "55460330457175623c000000",
      name: "task_0",
      start_at: "2015-05-03T11:14:56+00:00",
      user: "550419ed45717562b0000000"
    }, {
      done: false,
      id: "55460330457175623c010000",
      name: "task_1",
      start_at: "2015-05-04T11:14:56+00:00",
      user: "550419ed45717562b0000000"
    }
  ];
  newTask = {
    done: false,
    id: "55460330457175623c001000",
    name: "task_2",
    start_at: "2015-05-03T11:15:56+00:00",
    user: "550419ed45717562b0000000"
  };
  beforeEach(module('todoListsApp'));
  beforeEach(inject(function($injector) {
    Task = $injector.get('Task');
    $httpBackend = $injector.get('$httpBackend');
    $httpBackend.when('GET', '/tasks').respond(testTasks);
    return $httpBackend.when('POST', '/tasks', newTask).respond(newTask);
  }));
  return xdescribe("task", function() {
    it("loads tasks from server", function() {
      $httpBackend.expectGET('/tasks');
      Task.getList().then(function(tasks) {
        return expect(tasks).toEqual(testTasks);
      });
      return $httpBackend.flush();
    });
    return it("creates new task", function() {
      Task.post(newTask).then(function(response) {
        return expect(response.task).toEqual(newTask);
      });
      return $httpBackend.flush();
    });
  });
});

// ---
// generated by coffee-script 1.9.2