describe("ApplicationController", function() {
  var $authentication, $controller;
  $controller = void 0;
  $authentication = void 0;
  beforeEach(function() {
    module('todoListsApp');
    return inject(function(_$controller_, $injector) {
      $controller = _$controller_;
      return $authentication = $injector.get('Authentication');
    });
  });
  return describe("authentication", function() {
    var $scope;
    $scope = {};
    beforeEach(function() {
      return $controller("ApplicationController", {
        $scope: $scope,
        Authentication: $authentication
      });
    });
    it("logs in user", function() {
      var email, password;
      email = 'test@mail.com';
      password = 'password';
      spyOn($authentication, 'logIn').and.callThrough();
      $scope.logIn(email, password);
      return expect($authentication.logIn).toHaveBeenCalledWith(email, password);
    });
    return it("logs out user", function() {
      spyOn($authentication, 'logOut').and.callThrough();
      $scope.logOut();
      return expect($authentication.logOut).toHaveBeenCalled();
    });
  });
});

// ---
// generated by coffee-script 1.9.2